language: java
os: linux
dist: xenial
jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    # Maven dependencies and wrappers
    - $HOME/.m2

branches:
  only:
    - master

install: skip
script: cd java; ./mvnw -V verify