name: Build Java

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/build-java.yml
      - java/src/**/*
      - java/.mvn/**/*
      - java/pom.xml
      - java/mvnw
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/build-java.yml
      - java/src/**/*
      - java/.mvn/**/*
      - java/pom.xml
      - java/mvnw

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      # don't cancel running jobs even if one fails
      fail-fast: false
      matrix:
        # java 17 fails: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x2fcad999) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x2fcad999
        java: [8, 11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: maven
      - name: Build
        run: ./mvnw -V verify
        working-directory: java
